/**
 * Deploy the private-poll contract to a Midnight network (Preprod by default
 * via `npm run deploy`).
 *
 * Flow: build wallet from seed → sync → wait for faucet tNIGHT → register NIGHT
 * for DUST (fees) → deploy with the organizer's secret key as private state.
 *
 * Adapted from the create-mn-app hello-world template (Midnight.js 4.1.1,
 * wallet-sdk 1.2.0), extended with a witness and private state.
 */
import * as path from 'node:path';
import * as fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { WebSocket } from 'ws';
import * as Rx from 'rxjs';

import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';

import { Contract } from '../contracts/managed/private-poll/contract/index.js';
import { resolveNetwork, getOrCreateWallet, formatWalletBackupNotice, recordDeployment } from './network';
import { createWallet, persistWalletState, unshieldedToken, type WalletContext } from './wallet';
import { witnesses, createPollPrivateState } from './witnesses';

// @ts-expect-error Required for wallet sync
globalThis.WebSocket = WebSocket;

export const PRIVATE_STATE_ID = 'privatePollState';
export const PRIVATE_STATE_STORE = 'private-poll-state';
const DUST_WAIT_TIMEOUT_MS = 10 * 60 * 1000;
const QUESTION = process.env.POLL_QUESTION?.trim() || 'Should Midnight dApps default to private-by-design?';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const zkConfigPath = path.resolve(__dirname, '..', 'contracts', 'managed', 'private-poll');

if (!fs.existsSync(path.join(zkConfigPath, 'contract', 'index.js'))) {
  console.error('\n❌ Contract not compiled! Run: npm run compile\n');
  process.exit(1);
}

const compiledContract = CompiledContract.make('private-poll', Contract).pipe(
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets(zkConfigPath),
);

const { network, config: networkConfig } = resolveNetwork();
const WALLET = getOrCreateWallet(network);
{
  const notice = formatWalletBackupNotice(WALLET, network);
  if (notice) console.log(notice);
}

// ─── Providers ─────────────────────────────────────────────────────────────────

function createProviders(walletCtx: WalletContext) {
  // The SDK requires >= 16 chars. Set PRIVATE_STATE_PASSWORD in .env.preprod.
  const privateStatePassword = process.env.PRIVATE_STATE_PASSWORD?.trim() || 'Private-Poll-Dev-Placeholder-Pw';

  const walletProvider = {
    getCoinPublicKey: () => walletCtx.shieldedSecretKeys.coinPublicKey,
    getEncryptionPublicKey: () => walletCtx.shieldedSecretKeys.encryptionPublicKey,
    async balanceTx(tx: any, ttl?: Date) {
      const recipe = await walletCtx.wallet.balanceUnboundTransaction(
        tx,
        { shieldedSecretKeys: walletCtx.shieldedSecretKeys, dustSecretKey: walletCtx.dustSecretKey },
        { ttl: ttl ?? new Date(Date.now() + 30 * 60 * 1000) },
      );
      return walletCtx.wallet.finalizeRecipe(recipe);
    },
    submitTx: (tx: any) => walletCtx.wallet.submitTransaction(tx) as any,
  };

  const zkConfigProvider = new NodeZkConfigProvider(zkConfigPath);

  return {
    // Private state (the organizer's secret key) is stored encrypted, locally.
    privateStateProvider: levelPrivateStateProvider({
      privateStateStoreName: PRIVATE_STATE_STORE,
      accountId: walletCtx.unshieldedKeystore.getBech32Address().toString(),
      privateStoragePasswordProvider: () => privateStatePassword,
    }),
    publicDataProvider: indexerPublicDataProvider(networkConfig.indexer, networkConfig.indexerWS),
    zkConfigProvider,
    // Proofs are generated by the LOCAL proof server, so witnesses never leave this machine.
    proofProvider: httpClientProofProvider(networkConfig.proofServer, zkConfigProvider),
    walletProvider,
    midnightProvider: walletProvider,
  };
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const syncedState = (ctx: WalletContext) => Rx.firstValueFrom(ctx.wallet.state().pipe(Rx.filter((s) => s.isSynced)));

async function waitForProofServer(maxAttempts = 60): Promise<boolean> {
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      await fetch(networkConfig.proofServer, { signal: AbortSignal.timeout(3000) });
      return true;
    } catch (err: any) {
      const code = err?.cause?.code || err?.code || '';
      if (!['ECONNREFUSED', 'UND_ERR_CONNECT_TIMEOUT', 'UND_ERR_SOCKET', 'ENOTFOUND'].includes(code)) return true;
    }
    await sleep(2000);
  }
  return false;
}

async function waitForFunds(ctx: WalletContext, address: string) {
  const tNight = (await syncedState(ctx)).unshielded.balances[unshieldedToken().raw] ?? 0n;
  if (tNight > 0n || !networkConfig.faucet) return tNight;

  console.log('─── Fund Wallet ────────────────────────────────────────────────\n');
  console.log(`  Wallet address: ${address}`);
  console.log(`  Faucet:         ${networkConfig.faucet}\n`);
  console.log('  Paste the address into the faucet. Waiting for tNIGHT (poll every 10s)...');
  const start = Date.now();
  while (Date.now() - start < 15 * 60 * 1000) {
    await sleep(10_000);
    const bal = (await syncedState(ctx)).unshielded.balances[unshieldedToken().raw] ?? 0n;
    if (bal > 0n) {
      console.log(`\n  Funded! tNIGHT balance: ${bal.toLocaleString()}\n`);
      return bal;
    }
    process.stdout.write(`\r  ...still waiting (${Math.round((Date.now() - start) / 1000)}s)`);
  }
  throw new Error('Funding not received within 15 minutes. Re-run after funding — the seed is preserved.');
}

async function ensureDust(ctx: WalletContext) {
  console.log('─── DUST Setup ─────────────────────────────────────────────────\n');
  const state = await syncedState(ctx);
  const unregistered = state.unshielded.availableCoins.filter((c: any) => !c.meta?.registeredForDustGeneration);
  if (unregistered.length > 0) {
    console.log(`  Registering ${unregistered.length} NIGHT UTXO(s) for DUST generation...`);
    // The sign callback already signs every input — do not call signRecipe again.
    const recipe = await ctx.wallet.registerNightUtxosForDustGeneration(
      unregistered,
      ctx.unshieldedKeystore.getPublicKey(),
      (payload) => ctx.unshieldedKeystore.signData(payload),
    );
    await ctx.wallet.submitTransaction(await ctx.wallet.finalizeRecipe(recipe));
  }
  if (state.dust.balance(new Date()) === 0n) {
    console.log('  Waiting for DUST to accrue (pays transaction fees)...');
    await Rx.firstValueFrom(
      ctx.wallet.state().pipe(
        Rx.throttleTime(5000),
        Rx.filter((s) => s.isSynced && s.dust.balance(new Date()) > 0n),
        Rx.timeout({ first: DUST_WAIT_TIMEOUT_MS }),
      ),
    );
  }
  console.log('  DUST ready.\n');
}

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n╔══════════════════════════════════════════════════════════════╗');
  console.log(`║  Deploy Private Poll → ${network.padEnd(38)}║`);
  console.log('╚══════════════════════════════════════════════════════════════╝\n');

  const walletCtx = await createWallet({ network, networkConfig, seed: WALLET.seed });
  console.log('  Syncing wallet with network (can take several minutes on first run)...');
  const tick = setInterval(() => process.stdout.write('.'), 5000);
  await walletCtx.wallet.waitForSyncedState();
  clearInterval(tick);
  console.log('\n  ✓ Synced.\n');
  await persistWalletState(network, walletCtx);

  const address = walletCtx.unshieldedKeystore.getBech32Address().toString();
  console.log(`  Wallet address: ${address}`);
  const balance = await waitForFunds(walletCtx, address);
  console.log(`  tNIGHT balance: ${balance.toLocaleString()}\n`);

  await ensureDust(walletCtx);

  console.log('─── Deploy Contract ────────────────────────────────────────────\n');
  if (!(await waitForProofServer())) {
    throw new Error(`Proof server not reachable at ${networkConfig.proofServer}. Run: docker compose up -d proof-server`);
  }
  console.log(`  Proof server:  ${networkConfig.proofServer}`);
  console.log(`  Poll question: "${QUESTION}"`);
  console.log('  Generating proof and submitting deploy transaction...\n');

  const providers = createProviders(walletCtx);
  // The organizer's secret key: private state, stored locally only. The
  // contract constructor publishes just its hash (see organizerKey()).
  const initialPrivateState = createPollPrivateState();

  let deployed: Awaited<ReturnType<typeof deployContract>> | undefined;
  for (let attempt = 1; attempt <= 20 && !deployed; attempt++) {
    try {
      deployed = await deployContract(providers as any, {
        compiledContract: compiledContract as any,
        args: [QUESTION],
        privateStateId: PRIVATE_STATE_ID,
        initialPrivateState,
      });
    } catch (err: any) {
      const msg = `${err?.message ?? err} ${err?.cause?.message ?? ''}`;
      const dustShortage = /Not enough Dust|Insufficient Funds|could not balance dust/.test(msg);
      if (!dustShortage || attempt === 20) throw err;
      console.log(`  DUST still accruing, retrying in 5s (attempt ${attempt}/20)...`);
      await sleep(5000);
    }
  }

  const contractAddress = deployed!.deployTxData.public.contractAddress;
  console.log('  ✅ Contract deployed!\n');
  console.log(`  Network:          ${network}`);
  console.log(`  Contract address: ${contractAddress}`);
  console.log(`  Deploy tx id:     ${deployed!.deployTxData.public.txId}`);
  console.log(`  Block height:     ${deployed!.deployTxData.public.blockHeight}\n`);

  recordDeployment(network, contractAddress, address);
  console.log('  Saved to .midnight-state.json — view public state with: npm run status\n');

  await persistWalletState(network, walletCtx);
  await walletCtx.wallet.stop();
}

main().then(
  () => process.exit(0),
  (err) => {
    console.error('\n❌', err);
    process.exit(1);
  },
);
